version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: phase-1
    schedule:
      interval: weekly
    rebase-strategy: auto
  - package-ecosystem: github-actions
    directory: /
    target-branch: phase-1
    schedule:
      interval: weekly
    rebase-strategy: auto
  - package-ecosystem: gradle
    directory: /
    target-branch: phase-2
    schedule:
      interval: weekly
    rebase-strategy: auto
  - package-ecosystem: github-actions
    directory: /
    target-branch: phase-2
    schedule:
      interval: weekly
    rebase-strategy: auto